import { useState } from 'react';
import { Plus, UserCog } from 'lucide-react';
import PageHeader from '../components/common/PageHeader.jsx';
import DataTable from '../components/common/DataTable.jsx';
import Drawer from '../components/common/Drawer.jsx';
import Modal from '../components/common/Modal.jsx';
import Badge, { toneFor } from '../components/common/Badge.jsx';
import { users as seed } from '../data/mockData.js';
export default function Users(){const [rows,setRows]=useState(seed);const [selected,setSelected]=useState(null);const [open,setOpen]=useState(false);const cols=[{key:'name',label:'Name'},{key:'email',label:'Email'},{key:'role',label:'Role'},{key:'status',label:'Status'},{key:'lastLogin',label:'Last Login'},{key:'risk',label:'Risk Score'},{key:'created',label:'Created'}];return <section className="page"><PageHeader title="User Management" subtitle="Create, edit, suspend, impersonate, and review internal admin users." actions={<button className="btn btn-primary" onClick={()=>setOpen(true)}><Plus size={17}/>Add User</button>}/><div className="filters"><input className="field" placeholder="Search users..."/><select className="field"><option>All statuses</option><option>Active</option><option>Pending</option><option>Suspended</option></select><select className="field"><option>All roles</option><option>Admin</option><option>Manager</option><option>Analyst</option></select></div><DataTable columns={cols} rows={rows} onRowClick={setSelected}/>{selected&&<Drawer title={selected.name} onClose={()=>setSelected(null)}><p><Badge tone={toneFor(selected.status)}>{selected.status}</Badge> <Badge tone={toneFor(selected.risk)}>{selected.risk} risk</Badge></p><p><b>Email:</b> {selected.email}</p><p><b>Role:</b> {selected.role}</p><p><b>Department:</b> {selected.department}</p><div className="ai-panel"><h3>AI user summary</h3><p>{selected.name} has normal usage patterns, last login was {selected.lastLogin}, and current permission scope matches the assigned {selected.role} role.</p></div><div className="grid grid-2" style={{marginTop:16}}><button className="btn btn-secondary"><UserCog size={17}/>Reset Password</button><button className="btn btn-danger">Suspend User</button></div></Drawer>}{open&&<Modal title="Add internal user" onClose={()=>setOpen(false)}><div className="form-grid"><div className="form-control"><label>Full name</label><input placeholder="Jane Cooper"/></div><div className="form-control"><label>Email</label><input placeholder="jane@company.com"/></div><div className="form-control"><label>Role</label><select><option>Admin</option><option>Manager</option><option>Analyst</option><option>Support Agent</option></select></div><div className="form-control"><label>Department</label><input placeholder="Operations"/></div></div><button className="btn btn-primary" style={{marginTop:18}} onClick={()=>{setRows([{id:'USR-NEW',name:'Jane Cooper',email:'jane@company.com',role:'Admin',department:'Operations',status:'Pending',lastLogin:'Never',risk:'Low',created:'Today'},...rows]);setOpen(false)}}>Create User</button></Modal>}</section>}
